### ISSUE TITLE
Change `_modInv` function to use builtin modexp precompile reduces cost

### ISSUE THREAD

**Issue by HarryR** [musalbas/solidity-BN256G2#2]
Cost of `ECTwistAdd` (before): 46479
Cost of `ECTwistAdd` (after): 28474

Correction: this won't decrease the cost of ECTwistMul, because translation from jacobian to affine is only done at the end, but any optimisations to the underlying jacobian addition routines will marginally affect the multiply operation.

However, because `sub(gas, 2000)` is being used, this needs to be marked as `view` rather than `pure`. You could hard-code the gas cost to `13653` and it should work, but it may break if the cost of the operation increases in future (unlikely).

```
    /**
     * This is about half as expensive has `_modInv` where `a` has with a high hamming weight
     * 
     *  result = pow(a, n-2, n)
     */
    function _modInvPrecompile(uint256 a, uint256 n)
        public view returns (uint256 result)
    {
        bool success;
        assembly {
            let freemem := mload(0x40)
            mstore(freemem, 0x20)
            mstore(add(freemem,0x20), 0x20)
            mstore(add(freemem,0x40), 0x20)
            mstore(add(freemem,0x60), a)
            mstore(add(freemem,0x80), sub(n, 2))
            mstore(add(freemem,0xA0), n)
            success := staticcall(sub(gas, 2000), 5, freemem, 0xC0, freemem, 0x20)
            result := mload(freemem)
        }
        require(success);
    }
```

**Comment by HarryR** [comment]
There are slight gas reductions you can make, but it increases code ugliness significantly, e.g. inlining the _FQ2Mul functions:

```solidity
            // W = z1 * z2
            (pt2zx,     pt2zy)     = (submod(mulmod(pt1zx, pt2zx, FIELD_MODULUS), mulmod(pt1zy, pt2zy, FIELD_MODULUS), FIELD_MODULUS),
					                  addmod(mulmod(pt1zx, pt2zy, FIELD_MODULUS), mulmod(pt1zy, pt2zx, FIELD_MODULUS), FIELD_MODULUS));

            (pt1xx,     pt1xy)     = _FQ2Sub(pt2yx, pt2yy, pt3[PTYX], pt3[PTYY]); // U = U1 - U2
            (pt1yx,     pt1yy)     = _FQ2Sub(pt2xx, pt2xy, pt3[PTZX], pt3[PTZY]); // V = V1 - V2
            
            // V_squared = V * V
            (pt1zx,     pt1zy)     = (submod(mulmod(pt1yx, pt1yx, FIELD_MODULUS), mulmod(pt1yy, pt1yy, FIELD_MODULUS), FIELD_MODULUS),
        	            			  addmod(mulmod(pt1yx, pt1yy, FIELD_MODULUS), mulmod(pt1yy, pt1yx, FIELD_MODULUS), FIELD_MODULUS));
        	            			  
            // V_squared_times_V2 = V_squared * V2
            (pt2yx,     pt2yy)     = (submod(mulmod(pt1zx, pt3[PTZX], FIELD_MODULUS), mulmod(pt1zy, pt3[PTZY], FIELD_MODULUS), FIELD_MODULUS),
                    				  addmod(mulmod(pt1zx, pt3[PTZY], FIELD_MODULUS), mulmod(pt1zy, pt3[PTZX], FIELD_MODULUS), FIELD_MODULUS));

            // V_cubed = V * V_squared
            (pt1zx,     pt1zy)     = (submod(mulmod(pt1zx, pt1yx, FIELD_MODULUS), mulmod(pt1zy, pt1yy, FIELD_MODULUS), FIELD_MODULUS),
                    				  addmod(mulmod(pt1zx, pt1yy, FIELD_MODULUS), mulmod(pt1zy, pt1yx, FIELD_MODULUS), FIELD_MODULUS));
        				  
            // newz = V_cubed * W
            (pt3[PTZX], pt3[PTZY]) = (submod(mulmod(pt1zx, pt2zx, FIELD_MODULUS), mulmod(pt1zy, pt2zy, FIELD_MODULUS), FIELD_MODULUS),
                    				  addmod(mulmod(pt1zx, pt2zy, FIELD_MODULUS), mulmod(pt1zy, pt2zx, FIELD_MODULUS), FIELD_MODULUS));
```

Reduces gas usage from 28474 to 28153. 

However, compiler runs into problems with stack limit being reached if you try to inline more statements than just those, so further reductions are even more painful.

This won't make any significant impact apart from the multiply operation, where it could save ~40-80k gas per multiply, otherwise ~300 gas reduction is insignificant.

**Comment by musalbas** [comment]
That looks great @HarryR. I think we should integrate the first optimisation. I guess we have to decide if we want to include a static gas cost, or change all the functions to view.

Static gas cost disadvantages: if there's a hard-fork to increase gas costs in the future, existing deployed contracts will break. Also if the gas cost decreases, won't transactions still have to include the same amount of gas (limit) if it's hard coded?
Dynamic gas cost disadvantages: since function headers will change, it will probably break existing Solidity code, but won't effect already deployed contracts.

@Schaeff what do you think? Would a dynamic gas cost/changing functions to view break compatibility with much code?

**Comment by musalbas** [comment]
Maybe another option could be to create a new ECTwistAdd, e.g. ECTwistAddPrecompile, that has a view header? But it would make the API look a bit ugly.

Or we could only change ECTwistAdd to view anyway, since it's the only function that needs modInv, and it's not called internally by any other function, since it only needs modInv to convert from Jacobian to affine. However this would mean ECTwistAdd would view and ECTwistMul would be pure, so it's also a bit ugly.

**Comment by 0xAshish** [comment]
@HarryR @musalbas I can create a PR !?

**Comment by HarryR** [comment]
Yes please do

**Comment by musalbas** [comment]
I think we should change functions to view and use sub(gas, 2000). It seems that the Solidity compiler still requires the function to be view even if the gas cost is hard-coded - see error below. Also, changing to view seems cleaner and this is how the precompiles for G1 are typically called anyway.

```
browser/Untitled.sol:24:24: TypeError: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
            success := staticcall(13653, 5, freemem, 0xC0, freemem, 0x20)
                       ^------------------------------------------------^```
